logFilters:
  - level: discard
    text: "em@workspace:. doesn't provide react-native (p52384), requested by react-native-gesture-handler."

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.1.cjs
