logFilters:
# react-native-web overrides react-native, so we don't need to have react-native installed
  - level: discard
    text: "em@workspace:. doesn't provide react-native (p52384), requested by react-native-gesture-handler."

nodeLinker: node-modules

