services:
  app:
    image: node:20
    container_name: em
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "echo ***Vite is running in Docker, use port 13000 on the host*** && npm start"
    ports:
      - "13000:3000"
    environment:
      - NODE_ENV=development
