import Path from '../@types/Path'
import State from '../@types/State'
import pathToThought from '../selectors/pathToThought'

// @MIGRATION_TODO: Fix all logic that uses headRank
/** Returns the rank of the thought displayed at the head of a Path. Note that in the context view the rank of the displayed thought is its rank among its own siblings, not its position in the context view, which is autogenerated by getContextsSortedAndRanked. */
const headRank = (state: State, path: Path): number | undefined => pathToThought(state, path)?.rank

export default headRank
