/** Wrap the input HTML in a wrapper node and return the HTML generated by doing so. Return the input HTML if the wrapper is null. */
const wrapHtml = (input: string, wrapper: HTMLElement | null): string => {
  if (!wrapper) return input

  const clone = wrapper?.cloneNode()

  if (!(clone instanceof HTMLElement)) return input

  clone.innerHTML = input

  return clone.outerHTML
}

export default wrapHtml
