import Path from '../@types/Path'
import SimplePath from '../@types/SimplePath'
import State from '../@types/State'
import Thunk from '../@types/Thunk'
import alert from '../actions/alert'
import moveThought from '../actions/moveThought'
import * as selection from '../device/selection'
import findDescendant from '../selectors/findDescendant'
import { getChildrenRanked } from '../selectors/getChildren'
import getNextRank from '../selectors/getNextRank'
import getRankBefore from '../selectors/getRankBefore'
import getThoughtBefore from '../selectors/getThoughtBefore'
import prevSibling from '../selectors/prevSibling'
import simplifyPath from '../selectors/simplifyPath'
import { registerActionMetadata } from '../util/actionMetadata.registry'
import appendToPath from '../util/appendToPath'
import ellipsize from '../util/ellipsize'
import head from '../util/head'
import headId from '../util/headId'
import headValue from '../util/headValue'
import parentOf from '../util/parentOf'
import { isContextStep } from '../util/pathStep'

export interface moveThoughtUpPayload {
  /** The caret offset within the cursor thought, read from the document before the move. */
  offset?: number | null
}

/** Swaps the thought with its previous siblings. */
const moveThoughtUp = (state: State, { offset }: moveThoughtUpPayload = {}): State => {
  const { cursor } = state

  if (!cursor) return state

  // The order of the contexts in a context view is autogenerated by getContextsSortedAndRanked, so reordering a
  // context has no visible effect and would silently move the Lexeme instance among its real siblings instead.
  if (isContextStep(head(cursor))) {
    return alert(state, { value: `Contexts may not be reordered in the context view.` })
  }

  const thoughtId = headId(cursor)
  const pathParent = parentOf(cursor) as Path
  const parentId = headId(pathParent)

  const prevThought = prevSibling(state, cursor)

  // if the cursor is on the first thought, move the thought to the end of its prev uncle
  // A context row's siblings are the other contexts, so a thought inside one has no uncle to move into — doing so
  // would take it out of the context view entirely. Decline rather than build a Path that names no rendered row.
  const prevUncleThought =
    pathParent.length > 0 && !isContextStep(head(pathParent))
      ? getThoughtBefore(state, simplifyPath(state, pathParent))
      : null
  const prevUnclePath = prevUncleThought ? appendToPath(parentOf(pathParent), prevUncleThought.id) : null

  if (!prevThought && !prevUnclePath) return state

  // metaprogramming functions that prevent moving
  if (findDescendant(state, thoughtId, '=readonly')) {
    return alert(state, {
      value: `"${ellipsize(headValue(state, cursor) ?? 'MISSING_THOUGHT')}" is read-only and cannot be moved.`,
    })
  } else if (findDescendant(state, thoughtId, '=immovable')) {
    return alert(state, {
      value: `"${ellipsize(headValue(state, cursor) ?? 'MISSING_THOUGHT')}" is immovable.`,
    })
  } else if (findDescendant(state, parentId, '=readonly')) {
    return alert(state, {
      value: `Subthoughts of "${ellipsize(headValue(state, parentOf(cursor)) ?? 'MISSING_THOUGHT')}" are read-only and cannot be moved.`,
    })
  } else if (findDescendant(state, parentId, '=immovable')) {
    return alert(state, {
      value: `Subthoughts of "${ellipsize(headValue(state, parentOf(cursor)) ?? 'MISSING_THOUGHT')}" are immovable.`,
    })
  }

  const rankNew = prevThought
    ? // previous thought
      getRankBefore(state, simplifyPath(state, pathParent).concat(prevThought.id) as SimplePath)
    : // first thought in previous uncle
      getNextRank(state, headId(prevUnclePath!))

  const newPathParent = prevThought ? pathParent : prevUnclePath!
  const newPath = appendToPath(newPathParent, thoughtId)

  return moveThought(state, {
    oldPath: cursor,
    newPath,
    ...(offset != null ? { offset } : null),
    newRank: rankNew,
    afterId: prevThought
      ? (prevSibling(state, appendToPath(pathParent, prevThought.id))?.id ?? null)
      : (getChildrenRanked(state, headId(prevUnclePath!)).at(-1)?.id ?? null),
  })
}

/**
 * Action-creator for moveThoughtUp. Reads the caret offset from the document, which the reducer cannot do itself without
 * reaching outside of state. It must be read before the move, since moveThought re-renders the editable.
 */
export const moveThoughtUpActionCreator = (): Thunk => dispatch =>
  dispatch({ type: 'moveThoughtUp', offset: selection.offset() })

export default moveThoughtUp

// Register this action's metadata
registerActionMetadata('moveThoughtUp', {
  undoable: true,
})
