import Path from '../@types/Path'
import SimplePath from '../@types/SimplePath'
import State from '../@types/State'
import Thunk from '../@types/Thunk'
import alert from '../actions/alert'
import moveThought from '../actions/moveThought'
import * as selection from '../device/selection'
import findDescendant from '../selectors/findDescendant'
import getPrevRank from '../selectors/getPrevRank'
import getRankAfter from '../selectors/getRankAfter'
import nextSibling from '../selectors/nextSibling'
import simplifyPath from '../selectors/simplifyPath'
import { registerActionMetadata } from '../util/actionMetadata.registry'
import appendToPath from '../util/appendToPath'
import ellipsize from '../util/ellipsize'
import head from '../util/head'
import headId from '../util/headId'
import headValue from '../util/headValue'
import parentOf from '../util/parentOf'
import { isContextStep } from '../util/pathStep'

export interface moveThoughtDownPayload {
  /** The caret offset within the cursor thought, read from the document before the move. */
  offset?: number | null
}

/** Swaps the thought with its next siblings. */
const moveThoughtDown = (state: State, { offset }: moveThoughtDownPayload = {}): State => {
  const { cursor } = state

  if (!cursor) return state

  // The order of the contexts in a context view is autogenerated by getContextsSortedAndRanked, so reordering a
  // context has no visible effect and would silently move the Lexeme context among its real siblings instead.
  if (isContextStep(head(cursor))) {
    return alert(state, { value: `Contexts may not be reordered in the context view.` })
  }

  const thoughtId = headId(cursor)
  const pathParent = parentOf(cursor) as Path
  const parentId = headId(pathParent)
  const nextThought = nextSibling(state, cursor)

  // if the cursor is the last child, move the thought to the beginning of its next uncle
  // A context row's siblings are the other contexts, so a thought inside one has no uncle to move into — doing so
  // would take it out of the context view entirely. Decline rather than build a Path that names no rendered row.
  const nextUncleThought =
    pathParent.length > 0 && !isContextStep(head(pathParent)) ? nextSibling(state, pathParent) : null
  const nextUnclePath = nextUncleThought ? appendToPath(parentOf(pathParent), nextUncleThought.id) : null

  if (!nextThought && !nextUnclePath) return state

  if (findDescendant(state, thoughtId, '=readonly')) {
    return alert(state, {
      value: `"${ellipsize(headValue(state, cursor) ?? 'MISSING_THOUGHT')}" is read-only and cannot be moved.`,
    })
  } else if (findDescendant(state, thoughtId, '=immovable')) {
    return alert(state, {
      value: `"${ellipsize(headValue(state, cursor) ?? 'MISSING_THOUGHT')}" is immovable.`,
    })
  } else if (findDescendant(state, parentId, '=readonly')) {
    return alert(state, {
      value: `Subthoughts of "${ellipsize(headValue(state, parentOf(cursor)) ?? 'MISSING_THOUGHT')}" are read-only and cannot be moved.`,
    })
  } else if (findDescendant(state, parentId, '=immovable')) {
    return alert(state, {
      value: `Subthoughts of "${ellipsize(headValue(state, parentOf(cursor)) ?? 'MISSING_THOUGHT')}" are immovable.`,
    })
  }

  const rankNew = nextThought
    ? // next thought
      getRankAfter(state, simplifyPath(state, pathParent).concat(nextThought.id) as SimplePath)
    : // first thought in next uncle
      getPrevRank(state, headId(nextUnclePath!))

  const newPathParent = nextThought ? pathParent : nextUnclePath!
  const newPath = appendToPath(newPathParent, thoughtId)

  return moveThought(state, {
    oldPath: cursor,
    newPath,
    ...(offset != null ? { offset } : null),
    newRank: rankNew,
    afterId: nextThought ? nextThought.id : null,
  })
}

/**
 * Action-creator for moveThoughtDown. Reads the caret offset from the document, which the reducer cannot do itself without
 * reaching outside of state. It must be read before the move, since moveThought re-renders the editable.
 */
export const moveThoughtDownActionCreator = (): Thunk => dispatch =>
  dispatch({ type: 'moveThoughtDown', offset: selection.offset() })

export default moveThoughtDown

// Register this action's metadata
registerActionMetadata('moveThoughtDown', {
  undoable: true,
})
