import { act } from 'react'
import { importTextActionCreator as importText } from '../../actions/importText'
import { HOME_TOKEN } from '../../constants'
import exportContext from '../../selectors/exportContext'
import store from '../../stores/app'
import dispatch from '../../test-helpers/dispatch'
import initStore from '../../test-helpers/initStore'
import { setCursorFirstMatchActionCreator as setCursor } from '../../test-helpers/setCursorFirstMatch'
import head from '../../util/head'
import generateThought from '../generateThought'

/*
 * Live inference test for the Generate Thought command.
 *
 * Unlike the mocked unit tests in generateThought.ts, this test does NOT mock fetch. It executes the
 * Generate Thought command against the real AI server configured via VITE_AI_URL and asserts that the
 * server's response is parsed and applied to the thought.
 *
 * It is intentionally excluded from the normal unit run (see vitest.config.ts) and is only executed via
 * `yarn test:live` / the manually-triggered "Test AI (Live)" workflow, because it depends on a live
 * external service and non-deterministic model output.
 *
 * The AI server URL is read from the VITE_AI_URL environment variable, defaulting to the local dev server.
 */
const AI_URL = process.env.VITE_AI_URL || 'http://localhost:3111/ai'

beforeEach(() => {
  initStore()
  // initStore installs fake timers, but a live network request must resolve on real I/O.
  vi.useRealTimers()
  vi.stubEnv('VITE_AI_URL', AI_URL)
})

afterEach(() => {
  vi.unstubAllEnvs()
})

test('fill an empty thought with content generated by the live AI server', async () => {
  const text = `
      - Countries
        - France
          - Capital
            - ${''}
    `

  await dispatch([importText({ text }), setCursor(['Countries', 'France', 'Capital', ''])])

  // Execute the command's exec directly (rather than via executeCommand) so that the live network
  // request is fully awaited before assertions run. use act, otherwise the pending value (...) will
  // still be rendered.
  await act(async () => {
    await generateThought.exec(store.dispatch, store.getState, new Event('test'), { type: 'keyboard' })
  })

  const state = store.getState()

  // the live server must not have produced an error or rate limit
  expect(state.error).toBeFalsy()
  expect(state.alert?.value).not.toBe('Rate limit reached. Please try again later.')

  // the previously empty thought is now filled with non-empty, non-pending content
  const exported = exportContext(state, [HOME_TOKEN], 'text/plain')
  expect(exported).not.toContain('...')

  const cursorThought = state.thoughts.thoughtIndex[head(state.cursor!)]
  expect(cursorThought.value.trim().length).toBeGreaterThan(0)
}, 30000) // live model inference can take several seconds
