import GesturePath from '../@types/GesturePath'

/**
 * Centralized gesture path definitions for all commands.
 * Single source of truth for e2e and app; command files import from here.
 */

interface Gestures {
  [key: string]: GesturePath | GesturePath[]
}

const gestures: Gestures = {
  ARCHIVE_GESTURE: [
    'ldl',
    'ldlr',
    'lrdl',
    'lrdrl',
    'lrdldr',
    'lrdldlr',
    'ldru',
    'ldrlru',
    'ldllru',
    'ldlru',
    'lrdru',
    'lrdlru',
    'lrdldru',
    'lrdldlru',
  ],
  BIND_CONTEXT_GESTURE: 'rud',
  BUMP_THOUGHT_DOWN_GESTURE: 'drd',
  CATEGORIZE_GESTURE: 'lu',
  CLEAR_THOUGHT_GESTURE: 'rl',
  CLOSE_COMMAND_CENTER_GESTURE: 'd',
  CURSOR_BACK_GESTURE: 'r',
  CURSOR_FORWARD_GESTURE: 'l',
  DELETE_GESTURE: 'ldldl',
  GENERATE_THOUGHT_GESTURE: 'ur',
  INDENT_GESTURE: 'rlr',
  JUMP_BACK_GESTURE: 'lul',
  JUMP_FORWARD_GESTURE: 'rur',
  MOVE_THOUGHT_DOWN_GESTURE: 'dud',
  MOVE_THOUGHT_UP_GESTURE: 'udu',
  NEW_GRANDCHILD_GESTURE: 'rdrd',
  NEW_SUBTHOUGHT_GESTURE: [
    'rdr',
    'rdldr',
    'rdldlr',
    'rdldldr',
    'rldr',
    'rldlr',
    'rldldr',
    'rldldlr',
    'rdru',
    'rdrdru',
    'rdrdrru',
    'rdrdrdru',
    'rlru',
    'rdrlru',
    'rdrdlru',
    'rdrdrlru',
    'rdllru',
    'rdrdrd',
    'rdrdrrd',
    'rdrdrdrd',
    'rdlrd',
    'rdldrd',
    'rdldlrd',
    'rdlru',
    'rdldru',
    'rdldlru',
    'rdldldru',
    'rldru',
    'rldlru',
    'rldldru',
    'rldldlru',
  ],
  NEW_SUBTHOUGHT_TOP_GESTURE: 'rdu',
  NEW_THOUGHT_ABOVE_GESTURE: 'rul',
  NEW_THOUGHT_GESTURE: ['rd', 'rdldl', 'rdldld', 'rldl', 'rldld', 'rldldl'],
  NOTE_GESTURE: 'rdlr',
  OPEN_COMMAND_CENTER_GESTURE: 'u',
  OPEN_GESTURE_CHEATSHEET_GESTURE: 'rdld',
  OUTDENT_GESTURE: 'lrl',
  PROSE_VIEW_GESTURE: 'rudr',
  SELECT_ALL_GESTURE: 'ldr',
  SELECT_BETWEEN_GESTURE: 'rdl',
  SWAP_NOTE_GESTURE: 'ulr',
  SWAP_PARENT_GESTURE: 'ul',
  TOGGLE_CONTEXT_VIEW_GESTURE: 'ru',
  TOGGLE_SORT_GESTURE: 'lurd',
  TOGGLE_TABLE_VIEW_GESTURE: 'rdlu',
  UNCATEGORIZE_GESTURE: 'dr',
}

export default gestures
