import Index from './IndexType'
import ThoughtId from './ThoughtId'
import Timestamp from './Timestamp'

/** A single thought in local state that contains a map of children ThoughtIds. Persistence stores a narrower ThoughtPayload (see data-providers/treecrdt/payload.ts); parentId, rank, and childrenMap are derived from the tree on read. */
interface Thought {
  archived?: Timestamp
  /** Meta attributes keyed by value, otherwise keyed by ThoughtId. */
  childrenMap: Index<ThoughtId>
  created: Timestamp
  /** Thought is being dynamically generated by AI. */
  generating?: boolean
  id: ThoughtId
  lastUpdated: Timestamp
  parentId: ThoughtId
  /** Still loading from the database. */
  pending?: boolean
  rank: number
  /** Used to track if a space is required when merging two siblings/thoughts. */
  splitSource?: ThoughtId
  /** The public key of the user defined by a hash of their private access token. See: clientId (thoughtspaceSession). */
  updatedBy: string
  value: string
}

export default Thought
