import ThoughtId from './ThoughtId'
import Timestamp from './Timestamp'

/** Decoded document content and optional editor fields. Child order belongs to the document view. */
interface Thought {
  archived?: Timestamp
  created: Timestamp
  /** Thought is being dynamically generated by AI. */
  generating?: boolean
  /** Display-only placeholder shown on an empty thought while `generating` is true. Not persisted. */
  generatingPlaceholder?: string
  id: ThoughtId
  lastUpdated: Timestamp
  parentId: ThoughtId
  /** Formatting applied to the thought while it was empty, held until text is typed into it. In-memory only: it is not part of the persisted ThoughtPayload. See actions/formatSelection. */
  pendingFormat?: string
  /** Used to track if a space is required when merging two siblings/thoughts. */
  splitSource?: ThoughtId
  /** Writer identifier derived from the access token, not an authenticated public key. See: clientId (thoughtspaceSession). */
  updatedBy: string
  value: string
}

export default Thought
