import { describe, expect, it } from 'vitest'
import checkTauriVersions from '../check-tauri-versions.mjs'

/** A Cargo.lock holding the given crates, in the shape Cargo writes. */
const cargoLock = (crates: Record<string, string>) =>
  [
    '# This file is automatically @generated by Cargo.\nversion = 4',
    ...Object.entries(crates).map(
      ([name, version]) =>
        `[[package]]\nname = "${name}"\nversion = "${version}"\nsource = "registry+https://github.com/rust-lang/crates.io-index"`,
    ),
  ].join('\n\n')

/** A Yarn Berry yarn.lock resolving each descriptor list to the given version. */
const yarnLock = (entries: [string, string][]) =>
  [
    '# This file is generated by running "yarn install" inside your project.\n\n__metadata:\n  version: 8\n  cacheKey: 10c0',
    ...entries.map(
      ([descriptors, version]) =>
        `"${descriptors}":\n  version: ${version}\n  resolution: "${descriptors.split(', ')[0].replace(/@npm:.*/, '')}@npm:${version}"\n  languageName: node\n  linkType: hard`,
    ),
  ].join('\n\n')

describe('checkTauriVersions', () => {
  it('reports @tauri-apps/api a minor ahead of the tauri crate', () => {
    expect(
      checkTauriVersions({
        yarnLock: yarnLock([['@tauri-apps/api@npm:^2.12.1', '2.12.1']]),
        cargoLock: cargoLock({ tauri: '2.11.3', 'tauri-build': '2.6.3' }),
      }),
    ).toEqual([{ npmName: '@tauri-apps/api', npmVersion: '2.12.1', crateName: 'tauri', crateVersion: '2.11.3' }])
  })

  it('passes when only the patch versions differ', () => {
    expect(
      checkTauriVersions({
        yarnLock: yarnLock([['@tauri-apps/api@npm:^2.12.1', '2.12.1']]),
        cargoLock: cargoLock({ tauri: '2.12.3' }),
      }),
    ).toEqual([])
  })

  it('compares minor versions numerically', () => {
    expect(
      checkTauriVersions({
        yarnLock: yarnLock([['@tauri-apps/api@npm:^2.9.0', '2.9.0']]),
        cargoLock: cargoLock({ tauri: '2.90.0' }),
      }),
    ).toEqual([{ npmName: '@tauri-apps/api', npmVersion: '2.9.0', crateName: 'tauri', crateVersion: '2.90.0' }])
  })

  it('pairs each @tauri-apps/plugin-* package with its tauri-plugin-* crate', () => {
    expect(
      checkTauriVersions({
        yarnLock: yarnLock([
          ['@tauri-apps/api@npm:^2.12.1', '2.12.1'],
          ['@tauri-apps/plugin-opener@npm:^2.4.0', '2.4.0'],
        ]),
        cargoLock: cargoLock({ tauri: '2.12.1', 'tauri-plugin-opener': '2.5.4' }),
      }),
    ).toEqual([
      {
        npmName: '@tauri-apps/plugin-opener',
        npmVersion: '2.4.0',
        crateName: 'tauri-plugin-opener',
        crateVersion: '2.5.4',
      },
    ])
  })

  it('reads every descriptor of an entry that several ranges resolved to', () => {
    expect(
      checkTauriVersions({
        yarnLock: yarnLock([['@tauri-apps/api@npm:^2.0.0, @tauri-apps/api@npm:^2.12.1', '2.12.1']]),
        cargoLock: cargoLock({ tauri: '2.11.3' }),
      }),
    ).toHaveLength(1)
  })

  it('skips a package or crate with no counterpart, as tauri build does', () => {
    expect(
      checkTauriVersions({
        yarnLock: yarnLock([
          ['@tauri-apps/cli@npm:^2.11.5', '2.11.5'],
          ['@tauri-apps/plugin-fs@npm:^2.4.0', '2.4.0'],
        ]),
        cargoLock: cargoLock({ 'tauri-build': '2.6.3', 'tauri-plugin-opener': '2.5.4' }),
      }),
    ).toEqual([])
  })
})
