name: Assign issue milestone

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write
  models: read

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - name: Set Node.js version
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install npm dependencies
        run: yarn

      - name: Assign milestone
        run: yarn milestone:assign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ',') }}
          ISSUE_MILESTONE: "${{ github.event.issue.milestone ? github.event.issue.milestone.number : '' }}"
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
