name: 'Copilot Setup Steps'

# Allow testing of the setup steps from your repository's "Actions" tab.
on: workflow_dispatch

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: yarn