name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  CI: true

jobs:
  run:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: yarn

      - name: Lint
        run: yarn lint
