name: Update Browserslist

on:
  schedule:
    # Run monthly on the 1st day of each month at 9:00 AM UTC
    - cron: '0 9 1 * *'
  workflow_dispatch: # Allow manual triggering

env:
  CI: true

jobs:
  update-browserslist:
    name: Update Browserslist
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: yarn

      - name: Update browserslist database
        run: |
          echo "Current browserslist database version:"
          npx browserslist --version || echo "browserslist not available"
          echo "Updating browserslist database..."
          npx update-browserslist-db@latest

      - name: Check for changes
        id: changes
        run: |
          echo "Checking for changes in the repository..."
          git status --porcelain
          if git diff --quiet; then
            echo "No changes detected"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected:"
            git diff --name-only
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update browserslist database'
          title: 'chore: update browserslist database'
          body: |
            This PR updates the browserslist database to the latest version.

            The browserslist database contains information about browser
            versions and their support for various web features. Keeping it up
            to date ensures that build tools and linters have the most current
            information about browser capabilities.

            This update was automatically generated by the Update Browserslist
            workflow.
          branch: update-browserslist
          delete-branch: true
