/** Here's documentation for all shortcuts. */

export { default as archive, archiveAliases } from './archive'
export { default as bindContext } from './bindContext'
export { default as bumpThoughtDown } from './bumpThoughtDown'
export { default as clearThought } from './clearThought'
export { default as collapseContext } from './collapseContext'
export { default as commandPalette } from './commandPalette'
export { default as copyCursor } from './copyCursor'
export { default as cursorBack } from './cursorBack'
export { default as cursorDown } from './cursorDown'
export { default as cursorForward } from './cursorForward'
export { default as cursorNext } from './cursorNext'
export { default as cursorPrev } from './cursorPrev'
export { default as cursorUp } from './cursorUp'
export { default as delete } from './delete'
export { default as deleteEmptyThoughtOrOutdent, deleteEmptyThoughtOrOutdentAlias } from './deleteEmptyThoughtOrOutdent'
export { default as devices } from './devices'
export { default as exportContext } from './exportContext'
export { default as extractThought } from './extractThought'
export { default as favorite } from './favorite'
export { default as generateThought } from './generateThought'
export { heading0, heading1, heading2, heading3, heading4, heading5 } from './headings'
export { default as help } from './help'
export { default as home } from './home'
export { default as indent } from './indent'
export { default as join } from './join'
export { default as jumpBack } from './jumpBack'
export { default as jumpForward } from './jumpForward'
export { default as moveCursorBackward } from './moveCursorBackward'
export { default as moveCursorForward } from './moveCursorForward'
export { default as moveThoughtDown } from './moveThoughtDown'
export { default as moveThoughtUp } from './moveThoughtUp'
export { default as newGrandChild } from './newGrandChild'
export { default as newSubthought, newSubthoughtAliases } from './newSubthought'
export { default as newSubthoughtTop } from './newSubthoughtTop'
export { default as newThoughtAbove } from './newThoughtAbove'
export { default as newThought, newThoughtAliases } from './newThought'
export { default as newUncle } from './newUncle'
export { default as note } from './note'
export { default as outdent } from './outdent'
export { default as pin } from './pin'
export { default as pinChildren } from './pinChildren'
export { default as proseView } from './proseView'
export { default as redo } from './redo'
export { default as search } from './search'
export { default as settings } from './settings'
export { default as splitSentences } from './splitSentences'
export { default as strikethrough } from './strikethrough'
export { default as subcategorizeAll } from './subcategorizeAll'
export { default as subcategorizeOne, subCategorizeOneShortcutAlias } from './subcategorizeOne'
export { default as textColor } from './textColor'
export { default as swapNote } from './swapNote'
export { default as toggleDone } from './toggleDone'
export { default as toggleContextView } from './toggleContextView'
export { default as toggleHiddenThoughts } from './toggleHiddenThoughts'
export { default as toggleSidebar } from './toggleSidebar'
export { default as toggleSort } from './toggleSort'
export { default as toggleSplitView } from './toggleSplitView'
export { default as toggleTableView } from './toggleTableView'
export { default as bold } from './bold'
export { default as italic } from './italic'
export { default as underline } from './underline'
export { default as undo } from './undo'
